/**
 * Theme management: pure `:root` palette overrides. The whole UI layout lives
 * in web/src/styles.css (single source); a theme is just a small CSS file that
 * overrides the :root CSS variables (--bg/--accent/--term-* plus derived ones
 * like --tooltip-bg/--code-bg). The frontend injects the theme file as a
 * <link> AFTER the bundled styles.css, so its :root variables win the cascade.
 * Builtin themes are generated by node make-light-theme.mjs.
 *
 * Theme sources (merged, user wins over builtin on id collision):
 *   - builtin: <pkgRoot>/themes/*.css   (ships with the npm package)
 *   - user   : <dataDir>/themes/*.css   (drop a css file here to add a theme)
 */
import { existsSync, readdirSync, readFileSync, statSync } from "node:fs";
import { join } from "node:path";

export interface ThemeInfo {
	id: string;
	name: string;
	builtin: boolean;
	nameEn?: string;
	group?: "classic" | "builtin";
}

/** Only simple file ids — no path traversal. */
const ID_RE = /^[A-Za-z0-9_-]+$/;

/** Display-name marker inside a theme css file (first lines):
 *  `/* theme-name: 中文名 *∕` — falls back to the file id when absent.
 *  `/* theme-name-en: English Name *∕` — optional English label; falls back
 *  to `name` when absent.
 *  Lets built-in AND user themes carry a human-readable label while the
 *  filename stays ASCII (id must match ID_RE). */
const THEME_NAME_RE = /\/\*\s*theme-name:\s*(.+?)\s*\*\//;
const THEME_NAME_EN_RE = /\/\*\s*theme-name-en:\s*(.+?)\s*\*\//;
const THEME_GROUP_RE = /\/\*\s*theme-group:\s*(.+?)\s*\*\//;

function readDisplayName(path: string, fallback: string): string {
	try {
		const head = readFileSync(path, "utf8").slice(0, 400);
		return head.match(THEME_NAME_RE)?.[1]?.trim() || fallback;
	} catch {
		return fallback;
	}
}

function readDisplayNameEn(path: string): string | undefined {
	try {
		const head = readFileSync(path, "utf8").slice(0, 400);
		return head.match(THEME_NAME_EN_RE)?.[1]?.trim() || undefined;
	} catch {
		return undefined;
	}
}

function readGroup(path: string): "classic" | "builtin" {
	try {
		const head = readFileSync(path, "utf8").slice(0, 400);
		const g = head.match(THEME_GROUP_RE)?.[1]?.trim();
		if (g === "classic") return "classic";
	} catch {
		// ignore
	}
	return "builtin";
}

export function listThemes(builtinDir: string, userDir: string): ThemeInfo[] {
	const scan = (dir: string, builtin: boolean): ThemeInfo[] => {
		if (!existsSync(dir)) return [];
		return readdirSync(dir)
			.filter((f) => f.endsWith(".css"))
			.filter((f) => ID_RE.test(f.slice(0, -4)))
			.sort()
			.map((f) => {
				const path = join(dir, f);
				const id = f.slice(0, -4);
				const name = readDisplayName(path, id);
				const nameEn = readDisplayNameEn(path);
				const group = readGroup(path);
				return {
					id,
					name,
					builtin,
					group,
					...(nameEn ? { nameEn } : {}),
				};
			});
	};
	const builtin = scan(builtinDir, true);
	const user = scan(userDir, false);
	const seen = new Set<string>();
	return [...builtin, ...user]
		.filter((t) => (seen.has(t.id) ? false : (seen.add(t.id), true)))
		.sort((a, b) => a.name.localeCompare(b.name));
}

/** Resolve a theme id to its css file path (user dir first). */
export function resolveThemeFile(builtinDir: string, userDir: string, id: string): string | null {
	if (!ID_RE.test(id)) return null;
	const userPath = join(userDir, `${id}.css`);
	if (existsSync(userPath) && statSync(userPath).isFile()) return userPath;
	const builtinPath = join(builtinDir, `${id}.css`);
	if (existsSync(builtinPath) && statSync(builtinPath).isFile()) {
		return builtinPath;
	}
	return null;
}
